---
- name: Create new instances
  hosts: localhost
  roles:
    - { role: briochebcit.instance, tags: instance }

- name: Manage new webserver instances
  hosts: webservers
  connection: ssh
  become: true
  roles:
    - { role: briochebcit.webserver, tags: webserver }

- name: Manage new HAProxy servers
  hosts: lbservers
  connection: ssh
  become: true
  roles:
    - { role: briochebcit.loadbalancer, tags: loadbalancer}

- name: Manage new Munin servers
  hosts: muninservers
  connection: ssh
  become: true
  roles:
    - { role: briochebcit.monitoring, tags: monitoring }

