---
 - name: Ensure HAproxy is installed
   apt: pkg=haproxy state=installed

 - name: Ensure socat is installed
   apt: pkg=socat state=installed

 - name: Alter HA proxy config
   template: src=/etc/ansible/roles/briochebcit.loadbalancer/templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644

 - name: Restarting HA proxy
   service: name=haproxy state=restarted
