   - name: disable the server in HAproxy
     become: true
     shell:   echo "disable server back/{{ inventory_hostname }}" | sudo socat stdio /var/lib/haproxy/stats.sock
     delegate_to: "{{ item }}"
     with_items: groups.lbservers

   - name: Copy over template php file
     become: true 
     template: src=/etc/ansible/roles/briochebcit.rollingredeploy/templates/index.php.j2 dest=/var/www/html/index.php owner=root group=root mode=0644 force=yes

   - name: enabling server in HAproxy
     become: true
     shell: echo "enable server back/{{ inventory_hostname }}" | socat stdio /var/lib/haproxy/stats.sock
     delegate_to: "{{ item }}"
     with_items: groups.lbservers
